"""
report.py
---------
Generates downloadable PDF and CSV reports from a scan-result dictionary.
"""

import csv
import io

from fpdf import FPDF


class PDFReport(FPDF):
    """A branded PDF report matching the dashboard's colour scheme."""

    def header(self):
        self.set_fill_color(10, 20, 35)
        self.rect(0, 0, 210, 30, "F")
        self.set_text_color(90, 209, 255)
        self.set_font("Helvetica", "B", 18)
        self.set_xy(10, 8)
        self.cell(0, 10, "Phishing URL Detection Report", ln=True)
        self.set_font("Helvetica", "", 10)
        self.set_text_color(150, 200, 220)
        self.cell(0, 6, "Generated by Phishing URL Detection System", ln=True)
        self.ln(15)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(120, 120, 120)
        self.cell(0, 10, f"Page {self.page_no()}  |  Created by Amit Anil", align="C")


def _section_title(pdf: FPDF, title: str) -> None:
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(20, 30, 40)
    pdf.cell(0, 8, title, ln=True)
    pdf.set_draw_color(90, 209, 255)
    pdf.line(pdf.get_x(), pdf.get_y(), 200, pdf.get_y())
    pdf.ln(3)


def _kv_row(pdf: FPDF, key: str, value) -> None:
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(40, 40, 40)
    pdf.cell(55, 7, key)
    pdf.set_font("Helvetica", "", 10)
    pdf.multi_cell(0, 7, str(value))


def generate_pdf_report(scan: dict) -> bytes:
    """Builds a PDF report and returns it as raw bytes."""
    pdf = PDFReport()
    pdf.add_page()

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(60, 60, 60)
    pdf.multi_cell(0, 6, f"Scanned URL: {scan.get('url', '')}")
    pdf.multi_cell(0, 6, f"Scan Timestamp: {scan.get('timestamp', '')}")
    pdf.ln(4)

    _section_title(pdf, "Domain Information")
    _kv_row(pdf, "Domain:", scan.get("domain", "N/A"))
    _kv_row(pdf, "Suffix:", scan.get("suffix", "N/A"))
    _kv_row(pdf, "Subdomain:", scan.get("subdomain") or "None")
    _kv_row(pdf, "Valid URL:", "Yes" if scan.get("is_valid") else "No")
    _kv_row(pdf, "HTTPS Enabled:", "Yes" if scan.get("https") else "No")
    pdf.ln(3)

    _section_title(pdf, "Heuristic Checks")
    _kv_row(pdf, "Uses IP Address:", "Yes" if scan.get("has_ip") else "No")
    _kv_row(pdf, "Shortened URL:", "Yes" if scan.get("is_shortener") else "No")
    keywords = scan.get("keywords_found") or []
    _kv_row(pdf, "Suspicious Keywords:", ", ".join(keywords) if keywords else "None found")
    pdf.ln(3)

    _section_title(pdf, "WHOIS Domain Age")
    whois_info = scan.get("whois", {}) or {}
    if whois_info.get("error"):
        _kv_row(pdf, "Status:", whois_info["error"])
    else:
        _kv_row(pdf, "Age (days):", whois_info.get("age_days", "N/A"))
        _kv_row(pdf, "Newly Registered:", "Yes (<180 days)" if whois_info.get("is_new") else "No")
    pdf.ln(3)

    _section_title(pdf, "VirusTotal Report")
    vt = scan.get("virustotal", {}) or {}
    if vt.get("error"):
        _kv_row(pdf, "Status:", vt["error"])
    else:
        stats = vt.get("stats", {}) or {}
        _kv_row(pdf, "Malicious:", stats.get("malicious", 0))
        _kv_row(pdf, "Suspicious:", stats.get("suspicious", 0))
        _kv_row(pdf, "Harmless:", stats.get("harmless", 0))
        _kv_row(pdf, "Undetected:", stats.get("undetected", 0))
        _kv_row(pdf, "Timeout:", stats.get("timeout", 0))
    pdf.ln(3)

    _section_title(pdf, "Risk Assessment")
    _kv_row(pdf, "Risk Score:", f"{scan.get('risk_score', 0)} / 10")
    _kv_row(pdf, "Risk Level:", scan.get("risk_level", "N/A"))
    _kv_row(pdf, "Final Verdict:", scan.get("verdict", "N/A"))

    return bytes(pdf.output())


def generate_csv_report(scan: dict) -> bytes:
    """Builds a flat CSV report and returns it as raw bytes."""
    buffer = io.StringIO()
    writer = csv.writer(buffer)

    whois_info = scan.get("whois", {}) or {}
    vt = scan.get("virustotal", {}) or {}
    stats = vt.get("stats", {}) or {}

    writer.writerow(["Field", "Value"])
    writer.writerow(["URL", scan.get("url", "")])
    writer.writerow(["Timestamp", scan.get("timestamp", "")])
    writer.writerow(["Valid URL", scan.get("is_valid")])
    writer.writerow(["Domain", scan.get("domain")])
    writer.writerow(["Suffix", scan.get("suffix")])
    writer.writerow(["Subdomain", scan.get("subdomain")])
    writer.writerow(["HTTPS", scan.get("https")])
    writer.writerow(["Uses IP Address", scan.get("has_ip")])
    writer.writerow(["Shortened URL", scan.get("is_shortener")])
    writer.writerow(["Suspicious Keywords", ", ".join(scan.get("keywords_found") or [])])
    writer.writerow(["Domain Age (days)", whois_info.get("age_days")])
    writer.writerow(["Newly Registered", whois_info.get("is_new")])
    writer.writerow(["VT Malicious", stats.get("malicious")])
    writer.writerow(["VT Suspicious", stats.get("suspicious")])
    writer.writerow(["VT Harmless", stats.get("harmless")])
    writer.writerow(["VT Undetected", stats.get("undetected")])
    writer.writerow(["VT Timeout", stats.get("timeout")])
    writer.writerow(["Risk Score", scan.get("risk_score")])
    writer.writerow(["Risk Level", scan.get("risk_level")])
    writer.writerow(["Final Verdict", scan.get("verdict")])

    return buffer.getvalue().encode("utf-8")
